### ISSUE TITLE
Updates are pulling -SNAPSHOT builds

### ISSUE THREAD

**Issue by ftaylor** [NewAmazingPVP/AutoViaUpdater#10]
The Via updaters are pulling the *-SNAPSHOT builds from Jenkins.

```
java[1939814]: [11:16:04 INFO]: [ViaVersion] Enabling ViaVersion v5.2.2-SNAPSHOT
java[1939814]: [11:16:04 INFO]: [ViaBackwards] Enabling ViaBackwards v5.2.2-SNAPSHOT
java[1939814]: [11:16:04 INFO]: [ViaRewind-Legacy-Support] Enabling ViaRewind-Legacy-Support v1.5.2
...
java[1941275]: [11:16:05 INFO]: [ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
```

These are more frequent builds (more like dev).  Can you add an option to ignore these versions?

**Comment by NewAmazingPVP** [comment]
@ftaylor You are right, it does pull the latest SNAPSHOT builds from Jenkins. That's actually the feature because if you look at their Jenkins https://ci.viaversion.com/job/ViaVersion/ and click on the non-dev version, all of their jars are named -SNAPSHOT at the end. If you look at their dev versions, those don't have *-SNAPSHOT after them. This plugin currently gets all the Vias from Jenkins, and therefore it will download the latest snapshots. If you wish to not download these SNAPSHOTS, what you can do is use [AutoUpdatePlugins,](https://www.spigotmc.org/resources/autoupdateplugins.109683/) where you can manually specify where to download the latest builds from, like Spigot (https://www.spigotmc.org/resources/viaversion.19254/), PaperMC, Hangar, etc., and that should do the trick for you.

![Image](https://github.com/user-attachments/assets/bfd1cc56-f329-4fe3-bd65-e5e5e9105e3f)

![Image](https://github.com/user-attachments/assets/33a274d3-0a5d-4a86-9438-d851a38b9981)

![Image](https://github.com/user-attachments/assets/c07f0324-a41f-477b-9fed-4cd3c4c414e2)

**Comment by ftaylor** [comment]
@NewAmazingPVP While it is true that _most_ of their builds are labeled with -SNAPSHOT, those are their nightly/snapshot builds.  If you look more closely, their release builds _do not_ have -SNAPSHOT.  Their current release is  5.2.1 [1], and that job was created Jan 1 and it does not include the word -SNAPSHOT [2].

[1] https://github.com/ViaVersion/ViaVersion

[2] https://ci.viaversion.com/job/ViaVersion/1067/

Snapshots are a type of development release (as it says in the output).

**Comment by NewAmazingPVP** [comment]
You are correct. Never actually realized that distinction in their builds and assumed their jenkins just had snapshots, but now it does make it sense! I will go ahead and add an option to ignore those builds. Thank you for informing me.

**Comment by ftaylor** [comment]
I've been thinking about how best to approach this.  It looks like the Jenkins jobs last successful build is not really what we want because they are mostly the snapshots.  The latest stable build is:
#1118 (Apr 13, 2025, 2:39:06 PM)
but that is difficult to find programatically.

If you go to https://github.com/ViaVersion/ViaVersion/releases/latest (`curl -v https://github.com/ViaVersion/ViaVersion/releases/latest`), the location shows where the latest release is:

`curl -v https://github.com/ViaVersion/ViaVersion/releases/lates`
`< location: https://github.com/ViaVersion/ViaVersion/releases/tag/5.3.2`
 
Then at least you can grab the release version and download it from:
https://github.com/ViaVersion/ViaVersion/releases/download/$release/ViaVersion-$release.jar
e.g.,
https://github.com/ViaVersion/ViaVersion/releases/download/5.3.2/ViaVersion-5.3.2.jar

**Comment by NewAmazingPVP** [comment]
@ftaylor I am so sorry for such a late reply! So what I ended up doing was I completely removed the old dev builds system (since they haven't updated those from over a year) but still kept the same config, so now the dev option actually triggers the snapshot builds. I will probably rename that option to "snapshot" instead of "dev" in the future to make it less confusing. Please try this [build](https://cdn.discordapp.com/attachments/1312252725626408991/1385819202962718810/AutoViaUpdater-snapshotBuild.jar?ex=68577435&is=685622b5&hm=165f8b1a71b0514ecb9376c593a234c8e7ae1f1b942acb8e2657612403ddedc2&) and let me know if it works as intended.

Here's the new config for your reference.
```yml
# AutoViaUpdater config
# For understanding the difference between release and snapshot builds visit: https://ci.viaversion.com/
# When dev is enabled snapshot ("-SNAPSHOT") builds will be used. Otherwise the latest non-snapshot build is used.
# All of the builds here are from Jenkins. If you want to use any other source use this plugin: https://www.spigotmc.org/resources/autoupdateplugins.109683/

ViaVersion:
  # Enable or disable ViaVersion updates (https://ci.viaversion.com/job/ViaVersion)
  enabled: true
  # Enable or disable snapshot builds from Jenkins
  dev: true
  # Enable or disable Java 8 builds (https://ci.viaversion.com/job/ViaVersion-Java8/)
  java8: false

ViaBackwards:
  # Enable or disable ViaBackwards updates (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/)
  enabled: true
  # Enable or disable snapshot builds from Jenkins
  dev: true
  # Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Java8/)
  java8: false

ViaRewind:
  # Enable or disable ViaRewind updates (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/)
  enabled: true
  # Enable or disable snapshot builds from Jenkins
  dev: true
  # Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-Java8/)
  java8: false

ViaRewind-Legacy:
  # Enable or disable ViaRewind-Legacy updates. Note: Will not do anything for Bungeecord servers. (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/)
  enabled: true
  # Enable or disable snapshot builds from Jenkins
  dev: true

# Check-Interval setting
# The interval (in minutes) to check for updates
Check-Interval: 60

# Experimental Cron Support
# Example "0 0 * * *" is daily at midnight
# Leave it blank "" to disable and use the Check-Interval
Cron-Expression: ""

# The number of seconds to wait after the server has fully loaded before starting the update checking process.
# Setting this value too low may cause errors.
# If errors occur while loading vias, try setting this value to 60 seconds or higher.
Delay: 5

# AutoRestart settings
# AutoRestart is whether the server will restart after an update
# AutoRestart-Delay is the delay in seconds before restarting
# AutoRestart-Message is the message that will be broadcasted before restarting
AutoRestart: false
AutoRestart-Delay: 60
AutoRestart-Message: '&cServer is restarting in 1 minute!'
```
