### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Munchyz22** [NewAmazingPVP/AutoViaUpdater#5]
Is there any way you could add an option in the config to automatically restart the server if a new ViaVersion, ViaBackwards, or ViaRewind is downloaded?

Thank You, i am really liking your plugin.

**Comment by NewAmazingPVP** [comment]
@Munchyz22 Sure I can add support for auto restart when I get time to. (Might take a while though, if that's okay)

**Comment by NewAmazingPVP** [comment]
@Munchyz22 I have added the feature, but I haven't had time to test it yet, so if you try out this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1299557513716568084/AutoViaUpdater-autoRestartFeature.jar?ex=671da2bf&is=671c513f&hm=c15e95e5b3c7249602eb404bc9981716e510062edd2507bac7c4429e697d6160&) that would be great! Please let me know if it works as intended or not.

**Comment by Munchyz22** [comment]
I added this build to my Minecraft server and deleted all Via's I had installed.  It did download the Via's and reboot the server automatically.  Although, It did not wait the 60 seconds after the download to reboot.

I will keep you updated when a new Via is released to make sure it reboots on my live server.

**Comment by NewAmazingPVP** [comment]
@Munchyz22 There was a small bug in the build that didn't take in the configured seconds for restart and the restart message, so here should be the fixed [build](https://cdn.discordapp.com/attachments/1103725182314614834/1299731033968869386/autoupdateplugins-1.0.jar?ex=671e445a&is=671cf2da&hm=91a23d7d5511707a3ec04dc6e28498936794aea594a55a13855644b2b23d5737&). Test it out and let me know if it works as intended (you might have to regenerate config.yml to see these options).

```yml
# AutoRestart settings
# AutoRestart is whether or not the server will restart after an update
# AutoRestart-Delay is the delay in seconds before restarting
# AutoRestart-Message is the message that will be broadcasted before restarting
AutoRestart: false
AutoRestart-Delay: 60
AutoRestart-Message: '&cServer is restarting in 1 minute!'
```
